import { Injectable } from '@angular/core';
import { getSeed, toShuffledWithSeed } from './util/random';
import { load, save } from './util/storage';

@Injectable({
  providedIn: 'root'
})
export class GameRepoService {
readonly #words: string[] = [
    'ACTION',
    'ACTIVE',
    'ACTUAL',
    'ANIMAL',
    'ANNUAL',
    'ANSWER',
    'ARTIST',
    'ASYLUM',
    'ATOMIC',
    'ATTACK',
    'BANANA',
    'BEAUTY',
    'BISHOP',
    'BORING',
    'BOTTLE',
    'BOTTOM',
    'BRIDGE',
    'BUBBLE',
    'BUTTON',
    'CAMERA',
    'CANDLE',
    'CARROT',
    'CASTLE',
    'CHANCE',
    'CHANGE',
    'CHEESE',
    'CHURCH',
    'CINEMA',
    'CIRCLE',
    'CIRCUS',
    'CLIENT',
    'CLOSED',
    'COFFEE',
    'COMEDY',
    'COMMON',
    'COUPLE',
    'CRADLE',
    'CREATE',
    'CUSTOM',
    'DAMAGE',
    'DENIAL',
    'DESIGN',
    'DEVICE',
    'DIRECT',
    'DOCTOR',
    'DRAGON',
    'EMPIRE',
    'ENERGY',
    'ENGINE',
    'ESTATE',
    'EXPERT',
    'FACTOR',
    'FAMILY',
    'FAMOUS',
    'FATHER',
    'FEMALE',
    'FIGURE',
    'FINGER',
    'FINISH',
    'FLIGHT',
    'FLOWER',
    'FOREST',
    'FORMAL',
    'FOSSIL',
    'FRIEND',
    'FROZEN',
    'FUTURE',
    'GALAXY',
    'GARDEN',
    'GARLIC',
    'GENDER',
    'GENIUS',
    'GROUND',
    'GUITAR',
    'HEALTH',
    'HIDDEN',
    'HONEST',
    'HUNTER',
    'IMPACT',
    'INFANT',
    'INJURY',
    'ISLAND',
    'JUNGLE',
    'KIDNEY',
    'KILLER',
    'KNIGHT',
    'LAWYER',
    'LEAGUE',
    'LEGEND',
    'LENGTH',
    'LIQUID',
    'LISTEN',
    'LITTLE',
    'LUXURY',
    'MAGNET',
    'MANUAL',
    'MARKET',
    'MATRIX',
    'MATTER',
    'MEDIUM',
    'MEMBER',
    'MEMORY',
    'METHOD',
    'MIDDLE',
    'MINUTE',
    'MIRROR',
    'MODERN',
    'MOMENT',
    'MONKEY',
    'MOTHER',
    'MURDER',
    'MUSCLE',
    'MUSEUM',
    'NARROW',
    'NATION',
    'NATURE',
    'NORMAL',
    'NOTICE',
    'NUMBER',
    'OBJECT',
    'OFFICE',
    'ORACLE',
    'ORANGE',
    'ORIGIN',
    'PALACE',
    'PARADE',
    'PARENT',
    'PENCIL',
    'PEOPLE',
    'PERSON',
    'PLANET',
    'PLEASE',
    'POCKET',
    'POETRY',
    'POISON',
    'POLICY',
    'POTATO',
    'PRIEST',
    'PRINCE',
    'PRISON',
    'PUBLIC',
    'PURPLE',
    'PUZZLE',
    'RABBIT',
    'RANDOM',
    'RECIPE',
    'RECORD',
    'RELIEF',
    'REPORT',
    'RESCUE',
    'RETURN',
    'REVIEW',
    'RHYTHM',
    'ROCKET',
    'SAFETY',
    'SCHOOL',
    'SEASON',
    'SECOND',
    'SECRET',
    'SENIOR',
    'SHADOW',
    'SHIELD',
    'SIGNAL',
    'SILVER',
    'SIMPLE',
    'SINGLE',
    'SISTER',
    'SPIDER',
    'SPIRIT',
    'SQUARE',
    'STREET',
    'STRONG',
    'STUDIO',
    'STUPID',
    'SUPERB',
    'SWITCH',
    'TEMPLE',
    'THEORY',
    'THREAD',
    'TISSUE',
    'TONGUE',
    'TRAVEL',
    'TURKEY',
    'UNIQUE',
    'UPDATE',
    'VACUUM',
    'VALLEY',
    'VESSEL',
    'VICTIM',
    'VIOLIN',
    'VIRTUE',
    'VISION',
    'VISUAL',
    'VOLUME',
    'WEAPON',
    'WEIGHT',
    'WINDOW',
    'WIZARD',
    'WRITER',
    'YELLOW',
  ] as const;

#shuffledWords : string[] = [];

  #seed : number | null = null;
  #index : number | null = null;

  getWord(): Promise<string> {
    if (this.#shuffledWords.length === 0) {
      this.#seed = load<number>('seed');

      if (this.#seed === null) {
        this.#seed = getSeed();
        save('seed', this.#seed);
      }
      
      this.#shuffledWords = toShuffledWithSeed(this.#words, this.#seed);
    }

    const length = this.#shuffledWords.length;
    const lastIndex = this.#index ?? load<number>('index') ?? -1;
    this.#index = (lastIndex + 1) % length;
    save('index', this.#index);

    const word = this.#shuffledWords[this.#index];
    return Promise.resolve(word);
  }
}
